### ISSUE TITLE
Front-end UI Mockup

### ISSUE THREAD

**Issue by MisterPeModder** [KilianPAGEOT/DashFrame#4]

**Comment by Mathiso00** [comment]
![image](https://user-images.githubusercontent.com/113337793/199677357-de2596fe-cda9-43c4-acda-f5b286554013.png)
![image](https://user-images.githubusercontent.com/113337793/199677391-7690df76-cd7c-4783-b649-7b5bd136b740.png)
![image](https://user-images.githubusercontent.com/113337793/199677432-17d2f16b-cd39-4705-8236-44eab1568418.png)
